codestudio/codestudio/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls', 'index')),
    path('product/', include('product.urls', 'product')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

codestudio/index/urls.py
from django.urls import path

from . import views

app_name = 'index'

urlpatterns = [
    path('', views.index_page, name='index'),
    path('feedback/', views.feedback_view, name='feedback'),
    path('success/', views.feedback_success_view, name='feedback_success'),
    path('error/', views.feedback_error_view, name='feedback_error'),
]

codestudio/product/urls.py
from django.urls import path

from . import views

app_name = 'product'

urlpatterns = [
    path('<int:product_id>/', views.product_page, name='product_page'),
]

codestudio/product/models.py
from django.db import models


class Product(models.Model):
    title = models.CharField(max_length=200, verbose_name='заголовок продукта',
                             help_text='заголовок продукта до 200 знаков')
    image = models.ImageField(upload_to='product/', verbose_name='фото продукта',
                              help_text='фото продукта в формате .jpg или .png')
    alt = models.CharField(max_length=200, null=True, verbose_name='alt-текст фото',
                           help_text='alt-текст к фото продукта')

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'

    def __str__(self):
        return self.title


class TextList(models.Model):
    title = models.CharField(max_length=250, verbose_name='заголовок списка',
                             help_text='заголовок списка до 250 знаков')
    fk_product = models.ForeignKey(Product, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'список текста'
        verbose_name_plural = 'списки текста'

    def __str__(self):
        return self.title


class Point(models.Model):
    text = models.CharField(max_length=250, verbose_name='пункт списка', help_text='текст пункта до 250 знаков')
    fk_textlist = models.ForeignKey(TextList, related_name='points', on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'пункт списка'
        verbose_name_plural = 'пункты списка'

    def __str__(self):
        return self.text


class ProductSeo(models.Model):
    keywords = models.CharField(max_length=250, verbose_name='ключевые слова (keywords)',
                                help_text='SEO ключевые слова через запятую, до 250 знаков')
    description = models.CharField(max_length=200, verbose_name='описание (description)',
                                   help_text='SEO описание до 200 знаков')
    fk_product = models.ForeignKey(Product, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'seo-оптимизатор'
        verbose_name_plural = 'seo-оптимизатор (Product Page)'

    def __str__(self):
        return self.description

codestudio/product/views.py
from django.shortcuts import render

from .models import Product, TextList, ProductSeo, Point


def product_page(request, product_id):
    products = Product.objects.get(pk=product_id)
    text_lists = TextList.objects.all().prefetch_related('points')
    points = Point.objects.all()
    product_seo = ProductSeo.objects.last()

    context = {
        'products': products,
        'text_lists': text_lists,
        'points': points,
        'product_seo': product_seo,
    }
    return render(request, 'product.html', context)

codestudio/templates/error.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <title>Ошибка!</title>
</head>
<body>
    <div class="center">
        <h1>Произошла непредвиденная ошибка!</h1>
        <p>Ваше сообщение не отправлено. Пожалуйста, попробуйте ещё раз!</p>
        <a href="/">Вернуться на главную</a>
    </div>
</body>
</html>

codestudio/templates/index.html
{% load custom_filters %}

<!DOCTYPE html>
<html lang="ru">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, shrink-to-fit=no, viewport-fit=cover">
    <meta name="keywords" content="{{ indexes_seo.keywords }}">
    <meta name="description" content="{{ indexes_seo.description }}">
    <title>{{ indexes.title }}</title>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Piazzolla:wght@400;900&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="static/assets/css/swiper-bundle.min.css">
	<link rel="stylesheet" href="static/assets/css/style.css">
</head>
<body>
    <div class="wrapper">
        <div class="content">
            <h1>{{ indexes.title }}</h1>
            <div class="swiper-container">
                <div class="swiper-wrapper">
                    {% for slider in sliders %}
                        <div class="swiper-slide"><img src="{{ slider.image.url }}" alt="{{ slider.alt }}"></div>
                    {% endfor %}
                </div>
                <div class="swiper-button-next"></div>
                <div class="swiper-button-prev"></div>
            </div>
            <div class="intro-text">
                <p>{{ indexes.text|linebreaks }}</p>
            </div>
            <div class="products-list">
                <h2>Продукты</h2>
                <ul>
                    {% for product in products %}
                        <li><a href="{% url 'product:product_page' product.id %}">{{ product.title }}</a></li>
                    {% endfor %}
                </ul>
            </div>
            <div id="map" data-latitude="{{ locations.latitude|float_format }}" data-longitude="{{ locations.longitude|float_format }}"></div>
            <h2>Отправить сообщение</h2>

            <form method="post" action="{% url 'index:feedback' %}">
                    {% csrf_token %}
                <input type="text" name="name" placeholder="Ваше имя" class="text-box" id="name" name="name" maxlength="100" required>
                <input type="email" name="email" placeholder="Электронная почта" class="text-box" id="email" name="email" maxlength="320" required>
                <textarea name="message" cols="40" rows="10" placeholder="Сообщение" class="text-box" id="message" name="message" required></textarea>
                <button type="submit" class="button">Отправить</button>
            </form>
        </div>
    </div>
    <script src="https://api-maps.yandex.ru/2.1/?lang=ru_RU&amp;apikey=28ba27e6-8179-45dd-8a90-a542e1883e67" type="text/javascript"></script>
	<script src="static/assets/js/swiper-bundle.min.js"></script>
	<script src="static/assets/js/main.js"></script>
</body>
</html>

codestudio/templates/product.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, shrink-to-fit=no, viewport-fit=cover">
	<meta name="keywords" content="{{ product_seo.keywords }}">
	<meta name="description" content="{{ product_seo.description }}">
    <title>{{ products.title }}</title>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Piazzolla:wght@400;900&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
</head>
<body>
    <div class="wrapper">
        <div class="content">
            <a href="/" class="go-back">На главную</a>
                <h1>{{ products.title }}</h1>
                <img src="{{ products.image.url }}" alt="{{ products.alt }}" class="product-image">
            <div class="product-info">
                {% for text_list in text_lists %}
                    <div class="product-info-item">
                        <h2>{{ text_list.title }}</h2>
                        {% for point in text_list.points.all %}
                        <ul>
                            <li>{{ point.text }}</li>
                        </ul>
                        {% endfor %}
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
</body>
</html>

codestudio/templates/success.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <title>Спасибо за обращение</title>
</head>
<body>
    <div class="center">
        <h1>Спасибо за ваше сообщение!</h1>
        <p>Мы получили обращение и скоро с вами свяжемся.</p>
        <a href="/">Вернуться на главную</a>
    </div>
</body>
</html>